import 'dart:io';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../services/api_service.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import '../models/scan_model.dart';
import '../utils/theme.dart';
import '../utils/constants.dart';
import '../utils/text_styles.dart';
import '../widgets/custom_button.dart';
import '../widgets/loading_overlay.dart';
import 'package:intl/intl.dart';
import 'report_screen.dart';

class ScanScreen extends StatefulWidget {
  const ScanScreen({super.key});

  @override
  State<ScanScreen> createState() => _ScanScreenState();
}

class _ScanScreenState extends State<ScanScreen> {
  final ApiService _apiService = ApiService();
  final FirestoreService _firestoreService = FirestoreService();
  final AuthService _authService = AuthService();

  File? _selectedFile;
  bool _isAnalyzing = false;
  String? _selectedFileName;
  int _selectedFileSize = 0;

  Future<void> _pickApkFile() async {
    try {
      HapticFeedback.lightImpact();
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['apk', 'pdf'],
      );

      if (result == null || result.files.single.path == null) {
        return; // User cancelled
      }

      final file = File(result.files.single.path!);
      final fileName = result.files.single.name;
      final fileSize = result.files.single.size;

      // Validate extension
      final extension = fileName.split('.').last.toLowerCase();
      if (extension != 'apk' && extension != 'pdf') {
        _showErrorSnackBar('Invalid file type. Only .apk and .pdf files are supported.');
        return;
      }

      // Validate File Size (Max 100MB)
      final double sizeInMB = fileSize / (1024 * 1024);
      if (sizeInMB > AppConstants.maxFileSizeMB) {
        _showErrorSnackBar('File too large. Maximum size is ${AppConstants.maxFileSizeMB} MB.');
        return;
      }

      setState(() {
        _selectedFile = file;
        _selectedFileName = fileName;
        _selectedFileSize = fileSize;
      });
    } catch (e) {
      _showErrorSnackBar('Failed to pick file: $e');
    }
  }

  void _showErrorSnackBar(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AppColors.danger,
      ),
    );
  }

  Future<void> _startAnalysis() async {
    if (_selectedFile == null) return;

    HapticFeedback.mediumImpact();
    setState(() => _isAnalyzing = true);

    try {
      final user = _authService.getCurrentUser();
      if (user == null) throw 'User authentication required. Please log in again.';

      // Call API Service
      final response = await _apiService.analyzeFile(_selectedFile!);

      // Save to Firestore
      final scanModel = ScanModel(
        id: '', // Generated by Firestore
        userId: user.uid,
        fileName: _selectedFileName ?? 'Unknown File',
        fileType: response['file_type'] ?? (_selectedFileName?.toLowerCase().endsWith('.pdf') == true ? 'pdf' : 'apk'),
        packageName: response['package_name'],
        appName: response['app_name'],
        permissions: response['permissions'] != null ? List<String>.from(response['permissions']) : null,
        pages: response['pages'],
        isEncrypted: response['is_encrypted'],
        metadata: response['metadata'] != null ? Map<String, dynamic>.from(response['metadata']) : null,
        overallRisk: response['overall_risk'] ?? 0,
        riskLevel: response['risk_level'] ?? 'Low',
        scannedAt: DateTime.now(),
      );

      final docId = await _firestoreService.saveScanResult(scanModel);

      // Create model with the Firestore generated ID
      final savedScan = ScanModel(
        id: docId,
        userId: scanModel.userId,
        fileName: scanModel.fileName,
        fileType: scanModel.fileType,
        packageName: scanModel.packageName,
        appName: scanModel.appName,
        permissions: scanModel.permissions,
        pages: scanModel.pages,
        isEncrypted: scanModel.isEncrypted,
        metadata: scanModel.metadata,
        overallRisk: scanModel.overallRisk,
        riskLevel: scanModel.riskLevel,
        scannedAt: scanModel.scannedAt,
      );

      if (mounted) {
        setState(() {
          _isAnalyzing = false;
          _selectedFile = null;
          _selectedFileName = null;
          _selectedFileSize = 0;
        });

        // Navigate to Report Screen
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (_) => ReportScreen(scanModel: savedScan),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isAnalyzing = false);
        _showErrorDialog(e.toString());
      }
    }
  }

  void _showErrorDialog(String message) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          backgroundColor: AppColors.surface,
          title: Row(
            children: [
              const Icon(Icons.error_outline_rounded, color: AppColors.danger),
              const SizedBox(width: 8),
              Text('Analysis Failed', style: AppTextStyles.headingMedium.copyWith(fontSize: 18)),
            ],
          ),
          content: Text(
            message,
            style: AppTextStyles.bodyMedium,
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('OK'),
            ),
          ],
        );
      },
    );
  }

  void _clearSelectedFile() {
    HapticFeedback.lightImpact();
    setState(() {
      _selectedFile = null;
      _selectedFileName = null;
      _selectedFileSize = 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          SafeArea(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(AppSizes.paddingLarge),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Top Header
                  Text(
                    'File Scanner',
                    style: AppTextStyles.headingMedium.copyWith(color: AppColors.primary),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Analyze APK or PDF files for potential threats',
                    style: AppTextStyles.bodyMedium,
                  ),
                  const SizedBox(height: AppSizes.paddingLarge * 1.5),

                  // Upload Area
                  AnimatedSwitcher(
                    duration: const Duration(milliseconds: 300),
                    child: _selectedFile == null
                        ? _buildUploadPlaceholder()
                        : _buildFileCard(),
                  ),
                  const SizedBox(height: AppSizes.paddingLarge * 1.5),

                  // Analyze Button
                  CustomButton(
                    text: 'Analyze File',
                    icon: Icons.search_rounded,
                    onPressed: _selectedFile != null ? _startAnalysis : null,
                    isLoading: false, // Managed by full-screen overlay
                  ),
                  const SizedBox(height: AppSizes.paddingLarge * 1.5),

                  // Info Card Section
                  Container(
                    padding: const EdgeInsets.all(AppSizes.paddingMedium),
                    decoration: BoxDecoration(
                      color: AppColors.surface,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(color: AppColors.surface),
                    ),
                    child: Column(
                      children: [
                        _buildInfoRow('💡 Only scan files from trusted sources'),
                        const Divider(color: AppColors.background, height: 20),
                        _buildInfoRow('🔒 Your file is not stored — analyzed and discarded'),
                        const Divider(color: AppColors.background, height: 20),
                        _buildInfoRow('⚡ Analysis takes 10–60 seconds'),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),

          // Analysis Loading Overlay
          LoadingOverlay(
            isVisible: _isAnalyzing,
            onCancel: () {
              setState(() => _isAnalyzing = false);
            },
          ),
        ],
      ),
    );
  }

  Widget _buildUploadPlaceholder() {
    return InkWell(
      key: const ValueKey('upload_placeholder'),
      onTap: _pickApkFile,
      borderRadius: BorderRadius.circular(16),
      child: CustomPaint(
        painter: DashedBorderPainter(color: AppColors.primary.withAlpha(100)),
        child: Container(
          height: 250,
          alignment: Alignment.center,
          decoration: BoxDecoration(
            color: AppColors.surface.withAlpha(80),
            borderRadius: BorderRadius.circular(16),
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: AppColors.primary.withAlpha(20),
                  shape: BoxShape.circle,
                ),
                child: const Icon(
                  Icons.cloud_upload_outlined,
                  size: 48,
                  color: AppColors.primary,
                ),
              ),
              const SizedBox(height: AppSizes.paddingMedium),
              Text(
                'Tap to select APK or PDF file',
                style: AppTextStyles.bodyLarge.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 4),
              Text(
                'Supported: .apk, .pdf',
                style: AppTextStyles.caption,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildFileCard() {
    final formattedSize = AppConstants.formatFileSize(_selectedFileSize);
    final nowString = DateFormat('MMM dd, yyyy - hh:mm a').format(DateTime.now());
    final isPdf = _selectedFileName?.toLowerCase().endsWith('.pdf') == true;

    return Container(
      key: const ValueKey('file_card'),
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppColors.primary.withAlpha(55), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(20),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppSizes.paddingMedium),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: (isPdf ? Colors.red : AppColors.secondary).withAlpha(20),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Icon(
                        isPdf ? Icons.picture_as_pdf_rounded : Icons.android_rounded,
                        color: isPdf ? Colors.red : AppColors.secondary,
                        size: 24,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Text(
                      isPdf ? 'Selected PDF' : 'Selected APK',
                      style: AppTextStyles.bodyMedium.copyWith(fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
                TextButton(
                  onPressed: _clearSelectedFile,
                  child: Text(
                    'Change File',
                    style: AppTextStyles.caption.copyWith(
                      color: AppColors.danger,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const Divider(color: AppColors.background, height: 24),
            Text(
              _selectedFileName ?? 'Unnamed File',
              style: AppTextStyles.bodyLarge.copyWith(
                fontWeight: FontWeight.bold,
                fontSize: 18,
              ),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
            const SizedBox(height: 16),
            
            // Detail Grid
            Row(
              children: [
                Expanded(
                  child: _buildFileDetailItem('Size', formattedSize),
                ),
                Expanded(
                  child: _buildFileDetailItem('Selected At', nowString.split(' - ').first),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFileDetailItem(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: AppTextStyles.caption.copyWith(fontSize: 10, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 4),
        Text(
          value,
          style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textPrimary, fontWeight: FontWeight.w500),
        ),
      ],
    );
  }

  Widget _buildInfoRow(String text) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          child: Text(
            text,
            style: AppTextStyles.bodyMedium.copyWith(fontSize: 13),
          ),
        ),
      ],
    );
  }
}

class DashedBorderPainter extends CustomPainter {
  final Color color;
  final double strokeWidth;
  final double gap;
  final double dash;

  DashedBorderPainter({
    required this.color,
    this.strokeWidth = 1.5,
    this.gap = 5.0,
    this.dash = 8.0,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final Paint paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    final Path path = Path();
    path.addRRect(RRect.fromRectAndRadius(
      Rect.fromLTWH(0, 0, size.width, size.height),
      const Radius.circular(16),
    ));

    final Path dashPath = Path();
    for (final PathMetric metric in path.computeMetrics()) {
      double distance = 0.0;
      while (distance < metric.length) {
        final double len = dash;
        dashPath.addPath(
          metric.extractPath(distance, distance + len),
          Offset.zero,
        );
        distance += len + gap;
      }
    }
    canvas.drawPath(dashPath, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
